# Generated by Django 4.2.6 on 2023-11-28 05:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_product_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlesson',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='products', to='common.lesson'),
        ),
        migrations.AlterField(
            model_name='product',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
