# Generated by Django 4.2.6 on 2023-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_userlesson_created_userlesson_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viewedtime',
            name='end_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='viewedtime',
            name='start_time',
            field=models.PositiveIntegerField(),
        ),
    ]
