# Generated by Django 4.2.6 on 2023-11-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_userlesson_status_alter_viewedtime_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='last_viewed_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='viewed_times',
            field=models.ManyToManyField(blank=True, to='common.viewedtime'),
        ),
    ]
