# Generated by Django 4.2.6 on 2023-11-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_userlesson_last_viewed_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='total_viewed_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
